### ISSUE TITLE
Folder containing one app remains

### ISSUE THREAD

**Issue by rtybanana** [caughtinflux/Apex#6]
1. Tap and hold a group and drag it onto another single app to create a folder
2. Open the group inside the folder
3. Move the single app out of the folder
4. The grouped application will stay in the folder on it's own

Probably because it thinks its more than one app

**Comment by caughtinflux** [comment]
If you open the group inside the folder, that means you exited the wiggly
editing mode right? Then what you're seeing is stock iOS behaviour!

Aditya KD
http://caughtinflux.com

On 26-Jul-2016, at 10:27 PM, rtybanana notifications@github.com wrote:
1. Tap and hold a group and drag it onto another single app to create a
   folder
2. Open the group inside the folder
3. Move the single app out of the folder
4. The grouped application will stay in the folder on it's own

Probably because it thinks its more than one app

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/caughtinflux/Apex/issues/6, or mute the thread

**Comment by caughtinflux** [comment]
Definitely stock behaviour, closing this for now.

**Comment by rtybanana** [comment]
Hmm it seems you're right, I could've sworn that folders dissolved when a single app was held inside

Sorry, I'll keep checking around :)
